name: Terratest

#on:
#  pull_request:
#    paths:
#      - 'terraform/modules/**' test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Install Terratest
        run: go get github.com/gruntwork-io/terratest@v0.43.0

      - name: Run Terratest
        working-directory: ./test
        run: |
          go mod init test && go mod tidy -compat=1.17
          go test -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-2
